### ISSUE TITLE
So many error in this extension!!!!

### ISSUE THREAD

**Issue by fbens** [hguenot/yii2-gsftp#1]
### Undefined variable: user

``` php
# in D:\website\flxx2\basic\vendor\hguenot\yii2-gftp\FtpComponent.php at line 179
```

``` php
    public function login () {
        $this->connectIfNeeded(false);
        $this->handle->login();
        $this->onLogin(new Event(['sender' => $this, 'data' => $user]));
    }
```
### correct

`'data'=>$user` --> `'data' => $this->handle->user`

so many error in this extension,please check !

**Comment by hguenot** [comment]
Hi, Github is a collaborative platform. you could fork and make pull request for improving my work !!

Than for your help.
