### ISSUE TITLE
Versions confusion

### ISSUE THREAD

**Issue by ArsSirek** [hguenot/yii2-gsftp#11]
Hi @hguenot , thanks for the work on this project,
I am a bit confused with versions here, I started to use the project a year ago, and tried to update the system to work with php 7.2 now, There was an issue with the Object class name, but the actual problem for me turned out to be that composer doesn't update this repository automatically.

the error I received:
> PHP Fatal error:  Declaration of
 gftp\drivers\SftpDriver::get($remote_file, $local_file = NULL, $mode = gftp\drivers\FTP_ASCII, $asynchronous = false)
 must be compatible with
 gftp\drivers\RemoteDriver::get($remote_file, $local_file = NULL, $mode = gftp\drivers\FTP_ASCII, $asynchronous = false, ?callable $asyncFn = NULL)
 in ../vendor/hguenot/yii2-gsftp/drivers/SftpDriver.php on line 15

I see that the code on the github was updated with the [commit ](https://github.com/hguenot/yii2-gsftp/commit/d2d22ac70df744daf3bcee596a7641ac82aa4122) 
But can't get composer to see that.. which is probably an [issue to composer](https://github.com/composer/composer/issues/563), but I decided to post it here as I may be not the only one with the issue, it is fine with you, right?  

It worked only after I run an update with commit version 
>  composer require hguenot/yii2-gsftp dev-master#d2d22ac70df744daf3bcee596a7641ac82aa4122

But is there any other, recommended, way to update I missed?

**Comment by hguenot** [comment]
Hi @ArsSirek 

I've just created the release V1.1.2.
Have you try to use a released version instead of master branch in your composer ?

Maybe deleting entry in composer.lock file (or deleting this file) and running `composer update` could work...

HG
