### ISSUE TITLE
Interface differs from the FTP one.

### ISSUE THREAD

**Issue by ndobromirov** [hguenot/yii2-gsftp#13]
There is no mention about all the driver options and that there is a difference between this and the other driver.

There is at least one however - the `passive` flag.

If client is configured through the DSN, and has the passive flag present.
Once the configuration is changed from 
```php
        'componentName' => [
            'class' => 'app\components\FtpComponent',
            'connectionString' => 'ftp://user:pass@host:21',
            'driverOptions' =>  [
                'timeout' => 120,
                'passive' => 120,
            ],
        ],
```  
to 
```php
        'componentName' => [
            'class' => 'app\components\FtpComponent',
            'connectionString' => 'sftp://user:pass@host:22',
            'driverOptions' =>  [
                'timeout' => 120,
                'passive' => 120,
            ],
        ],
```  
It will fail to instantiate the client. This means that the two drivers are not the same and they are not interchangeable.

My porposal is to add a `passive` option to mimic the FTP driver and fully ignore it internally. Functionally it will be the same ini reality wil reduce chances of this issue.

**Comment by hguenot** [comment]
Hi,

First thank you for using this extension.
In my opinion, if you change protocol, it sounds logic the parameter are not the same.

Best regards.

**Comment by ndobromirov** [comment]
I was hoping to to be more transparent but overall I agree with you it is not something that is hard to fix once you hit it.
