### ISSUE TITLE
Setting unknown property: gftp\drivers\SftpDrive

### ISSUE THREAD

**Issue by albertodiaz** [hguenot/yii2-gsftp#3]
Hi, 

I have an issue with the connection to the sftp in linux, in windows works, I have the following error:

PHP Fatal error:  Uncaught exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: gftp\drivers\SftpDriver::handle' in .../vendor/yiisoft/yii2/base/Object.php:161

the configuration:

```
    'ftp' => [
        'class' => '\gftp\FtpComponent',
        'connectionString' => 'sftp://user:password@url:22',
        'driverOptions' => [ 'timeout' => 120 ]
    ],
```

Any idea? 

Regards

**Comment by hguenot** [comment]
Hi,

Could you give me more information like Yii version, complete stack trace, PHP version, etc.

Thanks for your help.

**Comment by albertodiaz** [comment]
Hi! thanks for you answer.

Php version: 5.6.7  
Yii version: 2.0.6

Complete stack trace:
PHP Fatal error:  Uncaught exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: gftp\drivers\SftpDriver::handle' in /var/www/test/vendor/yiisoft/yii2/base/Object.php:161
Stack trace:

```
    #0 /var/www/test/vendor/hguenot/yii2-gsftp/drivers/SftpDriver.php(189): yii\base\Object->__set('handle', NULL)
    #1 /var/www/test/vendor/hguenot/yii2-gftp/FtpComponent.php(205): gftp\drivers\SftpDriver->close()
    #2 /var/www/test/vendor/hguenot/yii2-gftp/FtpComponent.php(51): gftp\FtpComponent->close()
    #3 [internal function]: gftp\FtpComponent->__destruct()
    #4 {main}
      thrown in /var/www/test/vendor/yiisoft/yii2/base/Object.php on line 161
```

Best regards

**Comment by hguenot** [comment]
Hi,

I make some correction in SFtpDriver (`unset` function removes the object property).
Can you update, try again and let me know if it works ?

Best Regards.

**Comment by albertodiaz** [comment]
Thanks! that was fast!
The error is different, but still not working on linux

Exception 'gftp\FtpException' with message 'Could not login to SFTP server "myUrl" on port "22" with user "myUser".'

in /var/www/test/vendor/hguenot/yii2-gsftp/drivers/SftpDriver.php:156

Stack trace:
#0 /var/www/test/vendor/hguenot/yii2-gftp/FtpComponent.php(178): gftp\drivers\SftpDriver->login()
#1 /var/www/test/vendor/hguenot/yii2-gftp/FtpComponent.php(144): gftp\FtpComponent->login()
#2 /var/www/test/vendor/hguenot/yii2-gftp/FtpComponent.php(398): gftp\FtpComponent->connectIfNeeded()
#3 /var/www/test/console/controllers/SftpImporterController.php(93): gftp\FtpComponent->mdtm('/reports/last_s...')
#4 /var/www/test/console/controllers/SftpImporterController.php(70): console\controllers\SftpImporterController->getLastFileSFTP()
#5 /var/www/test/console/controllers/SftpImporterController.php(60): console\controllers\SftpImporterController->import()
#6 [internal function]: console\controllers\SftpImporterController->actionImport()
#7 /var/www/test/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#8 /var/www/test/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/test/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('import', Array)
#10 /var/www/test/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('import', Array)
#11 /var/www/test/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('sftp-importer/i...', Array)
#12 /var/www/test/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('sftp-importer/i...', Array)
#13 /var/www/test/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 /var/www/test/yii(31): yii\base\Application->run()
#15 {main}

**Comment by hguenot** [comment]
Are you sure you can connect from your Linux server to your SSH server (using sftp unix command) ?

**Comment by albertodiaz** [comment]
Yes, I can connect from the Linux server, I've just tried.

any other idea? 

thanks for your message

**Comment by hguenot** [comment]
Have you check the connection string is correctly parsed ? Can you try to connect directly with phpseclib ?

**Comment by hguenot** [comment]
Hi, 

Can you give me a feedback of the resolution ?

Thanks.

**Comment by albertodiaz** [comment]
Yep, I was going to write you soon.

I changed the configuration when I had the issue above,  basically, I removed the line
  'driverOptions' => [ 'timeout' => 120 ]

and without that line I got the gftp\FtpException

thanks!
