### ISSUE TITLE
Invalid configuration

### ISSUE THREAD

**Issue by nlrooat** [hguenot/yii2-gsftp#4]
Hi there,

When using the second configuration example from the using section, with the direct protocol, I get the following error:

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: gftp\FtpComponent::timeout

When removing the 'timeout' => 120 line, I get the following error:

Invalid Configuration – yii\base\InvalidConfigException
Object configuration must be an array containing a "class" element.

The basic usage configuration example works for me.

**Comment by hguenot** [comment]
Hello,
Sample configuration has been updated regarding this issue.

```
return [
    // [...]
    'components'=>[
        // [...]
        'ftp' => [
            'class' => '\gftp\FtpComponent',
            'driverOptions' => [
                'class' => \gftp\FtpProtocol::valueOf('sftp')->driver,
                'user' => 'me@somewhere.otrb',
                'pass' => 'PassW0rd',
                'host' => 'ssh.somewhere.otrb',
                'port' => 22,
                'timeout' => 120
            ]
        ]
    ],
    // [...]
];
```
