### ISSUE TITLE
Error when using ls('dirname',true,true)

### ISSUE THREAD

**Issue by diesonne** [hguenot/yii2-gsftp#5]
When using FtpComponent::ls() with both 'full' and 'recursive' parameters set to true an error is thrown: "Cannot use object of type stdClass as array"

The parse() method expects an array but receives objects

When setting the full param to false everything works fine

**Comment by hguenot** [comment]
Corrected : commit 1b3f033d1f7f28b20c4a5d9abedbe0926980e2bb
