### ISSUE TITLE
How to move remote file to another remote directory

### ISSUE THREAD

**Issue by vicmonmena** [hguenot/yii2-gsftp#7]
Hi!

I've been looking for a method to copy files in remote directories. Something like:

```
$remote_file = '/remote/directory/myfile.txt'
$remote_target_path = '/remote/directory/target/';

Yii::$app->ftp->movefile($remote_ofile, $remote_target_path);

```

I've tried using:

```
Yii::$app->ftp->rename($oldname, $newname);
```

But it does not work!

Any suggestion?

Thanks!

**Comment by vicmonmena** [comment]
Resolved using:

`Yii::$app->ftp->rename($oldname, $newname);`

**Comment by hguenot** [comment]
Sorry for the late response :(
And tanks for your help :)
