### ISSUE TITLE
how to call execute() function

### ISSUE THREAD

**Issue by nagbhushan** [hguenot/yii2-gsftp#8]
Hi,

I am able to SSH and list the files using ls command
$files = Yii::$app->gftp->ls();

but how to call the execute() function....??
$files = Yii::$app->gftp->execute("some command");

please let me know.

**Comment by nagbhushan** [comment]
Is anybody monitoring the issues we get.....???

**Comment by hguenot** [comment]
Hi,

First, please note that I am not at your disposal. So I answer when I can :o)

This is not yet possible but it seems that the underlying library (phpseclib) allow it.
You can freely add this functionality as this library is opensource. 

Best Regards

**Comment by nagbhushan** [comment]
Ohh sorry to make you feel as you are at my disposal.

Thanks for your reply.

I used another extension. It resolved the issue.
